### ISSUE TITLE
Update to Jakarta EE 8 APIs

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile#126]
Would be good to update to Jakarta EE 8 APIs as a base for a MP 4.0, possibly in Feb 2020

**Comment by kenfinnigan** [comment]
Here are the required tasks:

- [ ] [MP Umbrella](#141)
- [ ] [MP Config](https://github.com/eclipse/microprofile-config/issues/469)
- [ ] [MP Health](https://github.com/eclipse/microprofile-health/issues/214)
- [ ] [MP Metrics](https://github.com/eclipse/microprofile-metrics/issues/479)
- [ ] [MP Fault Tolerance](https://github.com/eclipse/microprofile-fault-tolerance/issues/467)
- [ ] [MP REST Client](https://github.com/eclipse/microprofile-rest-client/issues/231)
- [ ] [MP Open API](https://github.com/eclipse/microprofile-open-api/issues/383)
- [ ] [MP Open Tracing](https://github.com/eclipse/microprofile-opentracing/issues/161)
- [ ] [MP JWT Auth](https://github.com/eclipse/microprofile-jwt-auth/issues/137)
- [ ] [MP Reactive Streams Operators](https://github.com/eclipse/microprofile-reactive-streams-operators/issues/128)
- [ ] [MP Reactive Messaging](https://github.com/eclipse/microprofile-reactive-messaging/issues/75)
- [ ] [MP Context Propagation](https://github.com/eclipse/microprofile-context-propagation/issues/183)
- [ ] [MP LRA](https://github.com/eclipse/microprofile-lra/issues/248)
- [ ] [MP GraphQL](https://github.com/eclipse/microprofile-graphql/issues/103)

**Comment by Emily-Jiang** [comment]
done
