### ISSUE TITLE
MicroProfile 4.0 Platform Release Tracking

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile#169]
MicroProfile 4.0 Platform Specification can be released when the following component specs have been released:

- [ ] Config  ([Milestone](https://github.com/eclipse/microprofile-config/milestone/8)) ([Incompatible changes](https://github.com/eclipse/microprofile-config/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22MP+Config+2.0%22+label%3A%22incompatible+change+%3Awarning%3A%22))

- [ ] Fault Tolerance ([Milestone](https://github.com/eclipse/microprofile-fault-tolerance/milestone/9)) ([Incompatible changes](https://github.com/eclipse/microprofile-fault-tolerance/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0+label%3A%22Backward+Incompatible+Changes%22))

- [ ] Health ([Milestone](https://github.com/eclipse/microprofile-health/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0))

- [ ] JWT RBAC ([Milestone](https://github.com/eclipse/microprofile-jwt-auth/milestone/7))

- [ ] Metrics ([Milestone](https://github.com/eclipse/microprofile-metrics/milestone/6)) ([Incompatible changes](https://github.com/eclipse/microprofile-metrics/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0+label%3Aapi-breaking))

- [ ] Open API ([Milestone](https://github.com/eclipse/microprofile-open-api/milestone/2)) ([Incompatible changes](https://github.com/eclipse/microprofile-open-api/issues?q=is%3Aissue+milestone%3A%22MP+OpenAPI+2.0%22+label%3Aincompatible-changes+))

- [ ] Rest Client  ([Milestone](https://github.com/eclipse/microprofile-rest-client/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0))([Incompatible changes](https://github.com/eclipse/microprofile-rest-client/issues?q=is%3Aissue+milestone%3A2.0+label%3Abreaking-change+))

- [ ]  OpenTracing ([Milestone](https://github.com/eclipse/microprofile-opentracing/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0))

**Comment by radcortez** [comment]
@jclingan Don't forget to add OpenTracing :)

**Comment by rdebusscher** [comment]
@radcortez OpenTracing will no longer be part of the umbrella so that it can be replaced by OpenTelemetry in the coming months.

**Comment by radcortez** [comment]
From my understanding, there was no consensus about removing it from the platform just yet. If that is not correct, please point me to the decision about removing it :)

**Comment by kenfinnigan** [comment]
@rdebusscher, @radcortez is correct.

Though we had agreement back in November that we'd remove OpenTracing from the platform for MP 4.0, the last two hangouts have reversed that decision because others were concerned about the timing of any replacement.

**Comment by pavolloffay** [comment]
What is the status of this issue. The 4.0-m1 has been released https://github.com/eclipse/microprofile/releases/tag/4.0-M1. When is expected the final release?

**Comment by ederks85** [comment]
@pavolloffay The final release of MP 4.0 is blocked by finalising the MP Workgroup at Eclipse Foundation. Whenever this has been completed, MP 4.0 can ship as soon as the component specifications have made their final releases.

**Comment by ederks85** [comment]
@jclingan @kwsutter can you please review PR #188 that contains the changes for the RC1 release?

**Comment by ntrp** [comment]
Any updates on the state of the final release?

**Comment by xstefank** [comment]
MP 4.0 was released in December - https://github.com/eclipse/microprofile/releases/tag/4.0. I believe we just didn't close this issue. @jclingan ?

**Comment by ntrp** [comment]
Oh I was indeed confused by the fact that the current released version was 4.0.1
